# Generated by Django 5.1.4 on 2024-12-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pagecontent_sitesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contactform',
            name='last_name',
            field=models.CharField(default='Anonymous', max_length=50, verbose_name='Prénom'),
            preserve_default=False,
        ),
    ]
