# Generated by Django 5.1.4 on 2024-12-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_name_contactform_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nom de famille'),
        ),
    ]
